[workspace]
members = ["stat_mutex", "stat_message", "hash_mutex", "hash_message"]

[workspace.dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
rayon = "1.7"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.3.3", features = ["v4"] }
sha2 = "0.10.6"
